# Generated by Django 3.0.2 on 2020-01-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin_register',
        ),
        migrations.AlterField(
            model_name='book',
            name='course',
            field=models.CharField(default='12', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='filesize',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.CharField(default='science', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploadpath',
            field=models.CharField(default='uploads/', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='uploadstatus',
            field=models.CharField(default='success', max_length=30),
        ),
    ]
