# Generated by Django 3.0.2 on 2020-02-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_auto_20200108_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='filename',
            field=models.FileField(unique=True, upload_to='uploads/'),
        ),
    ]
